language: php
php:
  - "5.4"
  - "5.3"

before_script:
  - phpenv rehash
  - mysql -e 'create database xirm_ut;'
  - mysql xirm_ut < tests/unit/database/mysql.sql

script:
  - phpunit --configuration travisci-phpunit.xml